name: Downloader

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: "File URL"
        required: true
        type: string

jobs:
  download:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install aria2
        run: choco install aria2 -y

      - name: Create downloads folder
        run: mkdir downloads

      - name: Download file
        shell: powershell
        run: |
          $url = "${{ github.event.inputs.file_url }}"
          $filename = Split-Path $url -Leaf

          aria2c `
            -x 16 `
            -s 16 `
            -k 1M `
            -d downloads `
            -o $filename `
            $url

      - name: Commit downloaded file
        shell: powershell
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add downloads/*
          git commit -m "Add downloaded file"
          git push
